services:
  - type: web
    name: voter-validation-system
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: PORT
        value: 10000
